management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'health, info, ping, mappings'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
    info:
      cache:
        time-to-live: 2000ms
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://gateway.t3.nomis-api.hmpps.dsd.io/auth/issuer
  datasource:
    url: jdbc:h2:mem:interventions-catalogue-db;MODE=PostgreSQL
  jpa:
    show-sql: true
    properties:
      hibernate:
#        envers:
#          do_not_audit_optimistic_locking_field: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
flyway:
  enabled: true
graceful:
  shutdown:
    enabled: true
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

sns:
  endpoint:
    url: http://localhost:4575
  topic:
    arn: arn:aws:sns:eu-west-2:000000000000:interventions_event
  provider: localstack
#  aws:
#    access:
#      key:
#        id:
#    secret:
#      access:
#        key:
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
interventions:
  snsEnabled: false
